import ProductCard from "@/components/Ui/Card";
import { Divider } from "antd";
import Head from "next/head";
import { useRouter } from "next/router";

const SelectProduct = ({ data }) => {
  const router = useRouter();
  const { category } = router.query;

  return (
    <div className=" py-4">
       <Head>
        <title>Pc Builder | Select</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-center text-2xl text-gray-600 ">
        Select Your {category.toUpperCase()} Componets Below
      </h1>
      <Divider></Divider>
      <div className="grid grid-cols-3  gap-x-5 justify-items-center px-8 items-center justify-center mobile:grid-cols-1 tablet:grid-cols-2 desktop:grid-cols-3 ">
        {data?.data.map((products, key) => (
          <ProductCard key={key} link={false} products={products}></ProductCard>
        ))}
      </div>
    </div>
  );
};

export default SelectProduct;

// export const getStaticPaths = async () => {

//   const res = await fetch(`${process.env.SERVER_BASE_URL}/products`);
//   const data = await res.json();

//   const category = [
//     "cpu",
//     "motherboard",
//     "ram",
//     "power supply",
//     "monitor",
//     "ssd",
//   ];

//   const paths = category.map((category) => ({
//     params: { category },
//   }));

//   return {
//     paths,
//     fallback: false,
//   };
// };

export const getServerSideProps = async (context) => {
  // ?category=${category}
  const { category } = context.params;

  const res = await fetch(
    `${process.env.SERVER_BASE_URL}/products?category=${category}`
  );
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
};
