import Layouts from "@/components/Layouts";
import ProductCard from "@/components/Ui/Card";

import { Menu } from "antd";
import Head from "next/head";
import { useEffect, useState } from "react";
import { BiMemoryCard } from "react-icons/bi";
import {
  BsCpu,
  BsMemory,
  BsMotherboard,
  BsPower,
  BsThreeDots,
} from "react-icons/bs";
import { FiMonitor } from "react-icons/fi";

function getItem(label, key, icon, link) {
  return {
    key,
    icon,
    label: <a href={link}>{label}</a>,
  };
}

const items = [
  getItem("CPU", "cpu", <BsCpu />),
  getItem("MOTHERBOARD", "motherboard", <BsMotherboard />),
  getItem("RAM", "ram", <BsMemory />),
  getItem("POWER SUPPLY", "power supply", <BsPower />),
  getItem("MONITOR", "monitor", <FiMonitor />),
  getItem("STORAGE DEVICE", "ssd", <BiMemoryCard />),
  getItem("OTHERS", "others", <BsThreeDots />),
];

const Products = ({ data }) => {
  const [products, setProducts] = useState([]);
  // const { data } = useGetAllProductsQuery();

  const onClick = (e) => {
    
    setProducts(selectProduct(e.key));
  };

  useEffect(() => {
    setProducts(data?.data);
  }, [data]);
  
  const selectProduct = (category) => {
    const x = data?.data?.filter((product) => {
      if (product.category === category && category !== "others") {
        return product;
      } else if (
        category === "others" &&
        product.category !==
          ("monitor" &&
            "ssd" &&
            "power supply" &&
            "ram" &&
            "motherboard" &&
            "cpu")
      ) {
        return product;
        
      }
    });
    
    return x;
  };

  

  return (
    <div className="flex w-full flex-row p-4  ">
       <Head>
        <title>Pc Builder | Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu
        onClick={/* () => selectProduct("ram") */ onClick}
       /*  style={{
          width: 'auto',
        }} */

        className="w-auto tablet:w-[256px] mobile:w-[100px]"
        mode="vertical"
        items={items}
      />
      <div className="w-full p-8  grid grid-cols-4 gap-4 desktop:grid-cols-4 tablet:grid-cols-2 mobile:grid-cols-1  ">
        {products?.map((products, index) => (
          <ProductCard key={index} link={true} products={products}></ProductCard>
        ))}
      </div>
    </div>
  );
};
export default Products;

Products.getLayout = function getLayout(page) {
  return <Layouts>{page}</Layouts>;
};

export const getStaticProps = async () => {
  const res = await fetch(`${process.env.SERVER_BASE_URL}/products`);
  const data = await res.json();
  
  return {
    props: {
      data,
    },
  };
};
